const authors = [
"1997PastPaper",
"1998PastPaper",
"2000PastPaper",
"2005PastPaper",
"2017Collection",
"BT Kung",
"Cedric Chan",
"CM Lok",
"CM Tong",
"CP Wong",
"Grace Ho",
"Helen Chan",
"KC Cheng",
"KK Wong",
"KM Ma",
"KN Wong",
"KS Chu",
"Sam Wu",
"SC Wong",
"SK Cheung",
"TK Auyong",
"TK Leung",
"WH Ma",
"WT Ngai",
"WY Ho",
"YH Hui ",
"YL Leung"
];

const keywordsByTopic = [];

keywordsByTopic['1'] = [
"Acquisition",
"Anatomy",
"Attenuation correction",
"Brain death",
"Brain reach",
"Cerebrovascular reserve",
"Choroid plexus",
"Cutoff frequently",
"Data processing",
"ECD",
"FDG",
"Foramen",
"Histology",
"HMPAO",
"HMPAO vs ECD",
"Ictal study",
"Indication",
"Miscellaneous",
"Parkinsonism",
"Partial volume effect",
"Patient preparation",
"Physiology",
"PiB",
"Primary brain tumour",
"Quantitation",
"Radionuclide cisternography",
"Radiopharmaceutical",
"Uptake mechanism",
"Vasodilator"
];

keywordsByTopic['2'] = [
"Adenosine",
"Amyloidosis",
"Artefact",
"Atherosclerosis",
"BMIPP",
"Cardiac anatomy",
"Cardiac physiology",
"Cardiac sarcoidosis",
"Cardiac tracer",
"Cardiotoxicity",
"Contraindication",
"Coronary anatomy",
"Dipyridamole",
"Dobutamine",
"First-pass",
"Gated SPECT",
"Indication",
"Infarct imaging",
"Instrument",
"Lymphatic drainage",
"Lymphoscintigraphy",
"MIBG",
"MIBG scan",
"MUGA",
"Patient preparation",
"Polar map",
"Radiation reduction",
"Regadenoson",
"Sestamibi",
"Stress methodlogy",
"Stress methodology",
"Tetrofosmin",
"Thallium imaging",
"Thallium-201",
"Thrombus imaging",
"Treadmill stress test",
"Uptake mechanism",
"Vasodilator stress"
];

keywordsByTopic['3'] = [
"Adrenal cortical scintigraphy",
"Adrenal gland",
"APUDoma",
"Indication",
"MEN Iib",
"MIBG scan",
"NP-59",
"Octreotide",
"Osteoporosis",
"Parathormone",
"Parathyroid anatomy",
"Parathyroid scan",
"Perchlorate discharge test",
"Primary hyperaldosteronism",
"Primary hyperparathyroidism",
"Radioiodine",
"Radioiodine uptake test",
"Somatostatin receptors",
"T3 suppression",
"Thyroid anatomy",
"Thyroid hormone",
"Thyroid physiology",
"Thyroid scan",
"Thyroid uptake"
];

keywordsByTopic['4'] = [
"Bowel uptake",
"Denatured RBC",
"Gastric emptying",
"GI bleeding",
"Hepatic adenoma",
"IDA scan",
"IDA uptake",
"Liver colloid",
"Liver physiology",
"Meckel's scan",
"Miscellaneous",
"Morphine",
"RBC labelling",
"Sulphur colloid"
];

keywordsByTopic['5'] = [
"Acquisition",
"Captopril",
"Diuretic T1/2",
"DMSA",
"DMSA scan",
"F -15",
"Gates' method",
"GFR",
"MAG3 uptake",
"Obstruction",
"Quantitation",
"Radionuclide cystography",
"Renal physiology",
"Renal radiopharmaceutical",
"Renal scan",
"Renal transplant"
];

keywordsByTopic['6'] = [
"Blood cell labeling",
"Breath test",
"GFR",
"Laboratory NM",
"Radioiodine uptake test",
"Red cell volume",
"RIA",
"Schilling test"
];

keywordsByTopic['7'] = [
"Altered biodistribution",
"Antigranulocyte antibody",
"Gallium",
"HMPAO WBC",
"Indication",
"Indium WBC",
"Infection tracer",
"Infective endocarditis",
"Kinetics",
"Normal gallium",
"Normal HMPAO",
"Pathophysiology",
"Sensitivity",
"Uptake mechanism",
"WBC labelling"
];

keywordsByTopic['8'] = [
"Breast lymphatics",
"Breast SLN",
"Brown fat",
"Cancer incidence",
"Carcinoid",
"Cardiac amyloidosis",
"CEA",
"False positive I-131",
"FDG",
"FDG indication",
"Gallium scan",
"Gallium uptake",
"I-123 MIBG",
"Internal mammary node",
"Iodine scan",
"Liver MAA scan",
"Lymphatic drainage",
"Medullary thyroid carcinoma",
"Melanoma SLN",
"MIBG",
"MIBG quantitation",
"MIBG scan",
"MIBG uptake",
"MIBI uptake",
"Miscellaneous",
"Neuroblastoma FDG",
"Neuroblastoma prognosis",
"Octreotide scan",
"Oncoscint scan",
"Osteosarcoma",
"PERCIST",
"Phaeochromocytoma",
"Prostatic carcinoma",
"RECIST1.1",
"Scintimammography",
"SLN",
"SLN contraindication ",
"SLN false negative",
"SLN non-visualization",
"Thallium scan",
"Thyroid carcinoma",
"Tumour incidence",
"Tumour uptake",
"WGL vs ROLL"
];

keywordsByTopic['9'] = [
"Anatomy/Physiology",
"COAD",
"Contamination",
"COVID-19",
"Indication",
"Krypton-81m",
"Lung clearance",
"Lung nodule",
"Lung perfusion scan",
"MAA",
"Miscellaneous",
"Perfusion scan",
"Pertechnegas",
"Ventilation agent",
"VQ scan",
"Xenon-133"
];

keywordsByTopic['10'] = [
"Acquisition",
"Anatomy",
"BMD",
"Bone SPECT",
"Bone tumour",
"DXA",
"F-18 fluoride",
"Fracture risk",
"FRAX",
"HPOA",
"Image quality",
"Liver uptake",
"Lung uptake",
"MDP",
"MDP uptake",
"Metabolic bone disease",
"Multiple myeloma",
"Normal variant",
"Osteomyelitis",
"Osteoporosis",
"Patient preparation",
"Physiology",
"Radiation",
"Renal osteodystrophy",
"Renal uptake",
"Solitary lesion"
];

keywordsByTopic['11'] = [
"Acquisition",
"Bone growth pattern",
"Brain perfusion scan",
"Brown adipose tissue",
"Cancer incidence",
"Collimator",
"CT scan",
"DMSA scan",
"DXA",
"Dynamic renal scan",
"Dynamin renal scan",
"FDG uptake",
"First pass",
"GFR",
"HIDA Scan",
"Infection imaging",
"Lung perfusion scan",
"Lung scan",
"Meckel's scan",
"Milk scan",
"Miscellaneous",
"MUGA scan",
"Paediatric dosage",
"Paraganglioma",
"Radionculide cystography",
"Radionuclide cystography",
"Renal scan",
"Sedation",
"Thyroid",
"UTI"
];

keywordsByTopic['12'] = [
"Bone pain",
"I-131",
"Liver MAA",
"Liver MAA scan",
"MoAb",
"P-32",
"PRRT",
"Radiation induced liver disease",
"Radiobiology",
"Radioimmunotherapy",
"Radiolabelled peptide",
"Radiosynovectomy",
"Radium-223",
"SIRT",
"Somatostatin analogue",
"Strontium-89",
"Synovectomy",
"Zevalin"
];

keywordsByTopic['13'] = [
"Abdomen",
"Adrenal",
"Alzheimer's disease",
"Anterior mediastinum",
"Attenuation correction",
"Beam hardening",
"Brain",
"Brain quantification",
"Brown fat",
"Brown fat uptake",
"C-11 acetate",
"C-11 choline",
"C-11 methionine",
"C-11 PIB",
"C-11methionine",
"C-11thymidine",
"Cardiac anatomy",
"Cavernous sinus",
"Cervical lymph node",
"Common carotid artery",
"Contrast extravasation",
"Contrast media",
"Corticosteroid premedication",
"CT artifact",
"DOTATATE",
"Epilepsy",
"F-18 floride",
"FDG",
"FDG benign uptake",
"FDG brain",
"FDG false negative",
"FDG female genital",
"FDG normal",
"FDG patient preparation",
"FDG tumour uptake",
"FDG uptake mechanism",
"F-DOPA",
"Gallbladder uptake",
"Gallium-68",
"GLUT",
"Half life",
"HCC",
"Hounsfield unit",
"IASLC",
"Image artefact",
"Liver segment",
"Lymph node",
"Lymph nodes",
"Miscellaneous",
"Myocardial metabolism",
"Myocardial perfusion",
"N-13 ammonia",
"Nephrogenic systemic fibrosis",
"Neurology",
"O-15 water",
"Oncology",
"Pancreas",
"Pancreas uptake",
"Parametric image",
"Parapharyngeal space",
"Parkinson's disease",
"Patient preparation",
"Portosystemic collateral",
"PSMA",
"Pulmonary segment",
"Renal",
"Renal function assessment",
"Retroperitoneal space",
"Rubidium-82",
"Skull",
"Spinal cord",
"SUV",
"Thorax",
"Thymus",
"Uptake mechanism",
"Uterine cervix LN",
"Windowing"
];

keywordsByTopic['14'] = [
"Contrast media",
"Dacroscintigraphy",
"Diagnostic radionuclide",
"Lumbar puncture",
"Lymphoscintigraphy",
"Milestones",
"Monoclonal antibody",
"Radiotracer",
"Reporting",
"Salivary scan",
"Testicular scan",
"Uptake mechanism"
];