const authors = [
"2017Collection",
"BT Kung",
"CM Lok",
"CM Tong",
"CP Wong",
"KC Cheng",
"KK Wong",
"KM Ma",
"KN Wong",
"KS Chu",
"NY Pang",
"PT Choi",
"Sam Wu",
"SC Wong",
"Shiobhon Luk",
"SK Cheung",
"TK Auyong",
"WH Ma",
"WY Ho",
"YH Hui"
];

const keywordsByTopic = [];

keywordsByTopic['1'] = [
"Adenosine",
"Alzheimer's disease",
"Attenuation correction",
"Brain death",
"Brain maturation",
"Cerebrovascular disease",
"Cisternography",
"Dementia",
"Diamox",
"Epilepsy",
"Febrile seizure",
"Frontotemporal dementia",
"Luxury perfusion",
"Parkinsonism",
"Parkinson's disease",
"Progressive supranuclear palsy",
"Sydenham's chorea",
"Temporal lobe epilepsy",
"Vascular dementia"
];

keywordsByTopic['2'] = [
"Amyloidosis",
"Calcium score",
"Cardiac output",
"Chest pain",
"Dipyridamole",
"Dobutamine",
"Dual isotope",
"Effective half-life",
"Gated SPECT MPI",
"Heart failure",
"Herceptin",
"Hibernating myocardium",
"Hypertrophic cardiomyopathy",
"Indication",
"Insulin resistance",
"Large vessel vasculitis",
"LBBB",
"MIBI scan",
"MPI",
"MUGA scan",
"Myocardial infarction",
"Obesity paradox",
"PET perfusion",
"Prognostic indicator",
"Protocol",
"Radiation dose",
"Reconstruction artefact",
"Reverse redistribution",
"Right auricle",
"Sarcoidosis"
];

keywordsByTopic['3'] = [
"Amiodarone induced thyrotoxicosis",
"Congenital hyperinsulinism in infancy",
"Hypercortisolism",
"Hyperparathyroidism",
"Hypothyroidism",
"Insulinoma",
"Iodocholesterol scan",
"Parathyroid adenoma",
"Parathyroid scintigraphy",
"PTH assay",
"Struma ovarii ",
"Thyroid adenoma",
"Thyroid nodule",
"Thyroid uptake test",
"Thyrotoxicosis",
"Toxic thyroid nodule"
];

keywordsByTopic['4'] = [
"Accessory spleen",
"Acute cholecystitis",
"Bile acid diarrhea",
"CBD obstruction",
"Choledochal cyst",
"Denatured RBC scan",
"Focal nodular hyperplasia",
"GE reflux",
"GI bleeding",
"Haemangioma",
"Impaired fundic accomodation",
"Inflammatory bowel disease",
"Liver abscess",
"Liver segment",
"Meckel's scan",
"Prolonged oesophageal transit",
"Right isomerism",
"Splenosis"
];

keywordsByTopic['5'] = [
"Acute pyelonephritis",
"Acute tubular necrosis",
"Captopril scan",
"Deconvolution",
"Dehydration",
"DMSA",
"F-15",
"Hydration",
"Post micturition",
"Renal artery occlusion",
"Renal artery stenosis",
"Renal cell carcinoma",
"Renal failure",
"Renal perfusion",
"Renal transplant",
"Renal transplant obstruction",
"Renovacular hypertension",
"Transplant infarction",
"Urinoma",
"VU reflux"
];

keywordsByTopic['6'] = [
"Blood volume",
"Pernicious anaemia",
"Red cell mass",
"Red cell survival"
];

keywordsByTopic['7'] = [
"AIDS",
"Brown fat uptake",
"Charcot's joint",
"Chest infection",
"Chronic granulomatous disease",
"Drug induced hypersensitivity reaction",
"Infective endocarditis",
"Infective spondylodiscitis",
"Inflammatory bowel disease",
"Large vessel vasculitis",
"Osteomyelitis",
"Pelvic abscess",
"Prosthetic infection",
"Prosthetic joint infection",
"PUO",
"Pyelonephritis",
"Retroperitoneal fibrosis",
"Septic arthritis",
"Vertebral osteomyelitis"
];

keywordsByTopic['8'] = [
"Astrocytoma",
"Brain tumour",
"Breast SLN",
"Bronchogenic carcinoma",
"Cancer incidence",
"Carcinoid",
"CEA scan",
"Cervical cancer",
"GIST",
"HCC",
"HCC treatment",
"Hodgkin's lymphoma",
"IgG4- related disease",
"Karnofsky score",
"Langerhans cell histiocytosis",
"Liver metastasis",
"Lung cancer",
"Lymphoma",
"Malignant melanoma",
"Medullary carcinoma of thyroid",
"Metastatic phaeochromocytoma",
"Multiple Myeloma",
"Neuroblastoma",
"Neuroendocrine neoplasm",
"Non-Hodgkin's lymphoma",
"Oncogenic osteomalacia",
"Paeochromocytoma",
"Pancreatic adenocarcinoma",
"Paraganglioma",
"PERCIST",
"Phaeochromocytoma",
"Plasmacytoma",
"POEMS syndrome",
"Prostate cancer",
"PRRT",
"Radioembolization",
"RECIST1.1",
"Renal cell carcinoma",
"Smoldering multiple myeloma",
"Thyroid cancer"
];

keywordsByTopic['9'] = [
"AIDS",
"Altered biodistribution",
"Clinical application",
"Crus uptake",
"Intrapulmonary arteriovenous shunting",
"Lung cancer",
"Microembolus",
"Particle number",
"Perfusion-only",
"Pre-operative",
"Pulmonary clearance",
"Pulmonary embolism",
"Pulmonary hypertension",
"R-L shunt",
"Stripe sign",
"Technegas"
];

keywordsByTopic['10'] = [
"	Melorheostosis",
"Achilles tendinitis",
"Altered biodistribution",
"Ankylosing spondylitis",
"Bone infarct",
"bone tumor",
"Breast cancer",
"Child abuse",
"Chronic sclerosing osteomyelitis",
"Complex regional pain syndrome",
"Diabetic",
"DXA",
"DXA exclude vertebra",
"DXA FRAX",
"DXA height age",
"DXA LSC",
"Erdheim-Chester disease",
"Fibrodysplasia ossificans progressiva",
"Fibrous dysplasia",
"Fracture",
"Fragility fracture",
"FRAX",
"Haemangioma",
"Herniation pit",
"Heterotrophic ossification",
"HPOA",
"Hypophosphataemic osteomalacia",
"Injection granuloma",
"Ischiofemoral impingement",
"Ischiopubic synchondrosis",
"Liver metastasis",
"Mandibular condylar hyperplasia",
"Mazabraud syndrome",
"Metabolic bone disease ",
"Multifocal osteomyelitis",
"Multiple myeloma",
"Myositis ossificans",
"Osteitis condensans ilii",
"Osteoid osteoma",
"Osteomyelitis",
"Osteonecrosis",
"Osteopoikilosis",
"Osteoporosis",
"Osteoporosis treatment",
"Osteosarcoma",
"Paget's disease",
"Pelvic insufficiency fractures",
"Prostate cancer",
"Radiation nephritis",
"Raised ALP",
"Renal osteodystrophy",
"SAPHO syndrome",
"Scaphoid fracture",
"Sesamoiditis",
"Simple bone cyst",
"Soft tissue calcification",
"Spondylodiscitis",
"Spondylolysis",
"Sternal metastasis",
"Sternal uptake",
"Stress fracture",
"THR",
"Transient synovitis",
"Vertebral collapse"
];

keywordsByTopic['11'] = [
"	Caffey disease",
"Acute pyelonephritis",
"Adenitis",
"Biliary atresia",
"CHI",
"Congenital hypothyroidism",
"Congestive heart failure",
"Diffuse band heterotopia",
"Dysplastic left kidney",
"Ectopic thyroid",
"FOP",
"GCSF ",
"Hip pain",
"Knee pain",
"Meckel",
"MTSS",
"Neonatal jaundice",
"Neuroblastoma",
"Pars",
"Pendred Syndrome ",
"Perthes disease",
"Renal vein thrombosis",
"Sequestration lung",
"Splenogonadal fusion",
"Sport related injury",
"SWS",
"Testicular torsion"
];

keywordsByTopic['12'] = [
"Bone pain",
"Graves' disease",
"MIBG therapy",
"MIBG therpay",
"Octreotide scan",
"P-32",
"PRRT",
"Radiosynovectomy",
"Radium-223",
"SIRT",
"Theranostics ",
"Thyroid cancer",
"Thyrotoxicosis",
"Zevalin"
];

keywordsByTopic['13'] = [
"	Ga-68 PSMA",
"	Krukenberg tumor",
"Adnexal uptake",
"AIDS",
"Amyloid PET",
"Atheroma",
"Autoimmune thyroiditis",
"Benign bone tumour",
"Brain metastasis",
"Breast cancer",
"Brown adipose tissue",
"Cervical cancer",
"Chest pain",
"Choriocarcinoma",
"Colorectal cancer",
"Coronary artery disease",
"Crossed cerebellar diaschisis",
"CT imaging protocol",
"Dementia",
"Diffuse large B-cell lymphoma",
"Epilepsy",
"Esophageal cancer",
"Fasting",
"Focal nodular hyperplasia",
"Frontal lobe pilepsy",
"Giant cell arteritis",
"Hamartoma",
"Head and neck cancer",
"Hibernating myocardium",
"HIV",
"Hodgkin disease",
"Hodgkin's lymphoma",
"Hyperinsulinism",
"Hypertension",
"IgG4 related disease",
"Incidental thyroid nodule",
"Klatskin tumour",
"Krukenberg tumor",
"Langerhans cell histiocytosis",
"Lewy body dementia",
"Liver mass",
"Lung cancer",
"Lung nodule",
"Lymphoma",
"Medullary thyroid cancer",
"Movement disorder",
"Multiple Myeloma",
"Myocardial perfusion agent",
"Non-Hodgkin??s lymphoma",
"Oesophagea cancer",
"Ovarian cancer",
"Paratracheal mass",
"Patient preparation",
"Peritoneal plaques",
"PET brain tracer",
"POEMS",
"Prostate cancer",
"Radiation dose",
"Renal cell carcinoma",
"Rubidium-82",
"Solitary lung nodule",
"Stomach cancer",
"Temporal lobe pilepsy",
"Thymus",
"Thyroid cancer",
"Unknown primary"
];

keywordsByTopic['14'] = [
"Acute radiation syndrome",
"Darcyoscinitgraphy",
"Epididymitis",
"Ge-Ga generator",
"Generator QC",
"Lymphoscintigraphy",
"Menorrhagia",
"Neurofibromatosis",
"Omics",
"Personalized medicine ",
"Radiation Protection",
"Radiochemical purity",
"Scrotal scintigraphy",
"Statistics",
"Testicular Torsion"
];