const authors = [
"1997PastPaper",
"1998PastPaper",
"2000PastPaper",
"2005PastPaper",
"2017Collection",
"Anson Cheung",
"Bryan Lam",
"Cedric Chan",
"CM Lok",
"CM Tong",
"CT Tang",
"Eva Chan",
"Jacky Man Ki CHEUNG",
"John Lam",
"KK Wong",
"KM Ma",
"Louis Lee",
"Marco Lo",
"Martin Law",
"PM Wu",
"Raymond Ip",
"TK Auyong",
"TK Leung",
"WH Ma",
"WT Ngai",
"WY Ho",
"YH Wong"
];

const keywordsByTopic = [];

keywordsByTopic['1'] = [
"Adverse reaction",
"Altered biodistribution",
"Aseptic practice",
"Biodistribution",
"Biological tests",
"Cerebral perfusion agent",
"Chemical impurity",
"Chromatography",
"Clean room",
"Clearance of radiopharmaceutical",
"Dose calibrator",
"Dose labelling",
"Drug interaction",
"Equipment",
"Generator",
"Ideal radiopharmaceutical",
"Injection",
"Isolator",
"Laminar flow",
"MAA",
"Management of radioactive material",
"MDP",
"Measurement of radioactivity",
"Misadministration",
"Molybdenum-99",
"Organ dose",
"Oxidative state",
"Patient dosage",
"PET tracer",
"Physics in radiopharmaceutical",
"Production of radioisotope",
"Pyrogenicity",
"Quality control",
"Radiation dosimetry",
"Radiochemical purity",
"Radioembolization",
"Radiolabeling",
"Radionuclide",
"Radionuclidic impurity",
"Radiopharmaceutical",
"Radiopharmacy practice",
"Red cell labelling",
"Size",
"Specific activity",
"Standard operating procedure",
"Thallium-201",
"Therapeutic radiopharmaceutical",
"WBC labelling"
];

keywordsByTopic['2'] = [
"Artefact",
"Count rate response",
"Counter",
"Dead time",
"Detector material",
"Dose calibrator",
"Electromagnetic radiation",
"Finger dosimetry",
"Gas type proportional counter",
"Gas-filled detector",
"Geiger-Muller counter",
"Geometric efficiency",
"Intrinsic efficiency",
"Ionization chamber",
"Liquid scintillation counter",
"Minimum detectable activity",
"Multichannel analyzer",
"Photomultiplier tube",
"Pocket dosimeter",
"Radiation survey meter",
"Scintillator",
"Semiconductor",
"Sodium iodide well counter",
"Solid state detector",
"TLD"
];

keywordsByTopic['3'] = [
"Anger logic",
"Choice of collimator",
"Collimator",
"Collimator design",
"Component",
"Counting statistics",
"Dead time",
"Detector",
"Dynamic acquisition",
"Edge effect",
"Energy resolution",
"Field of view",
"Gamma spectrum",
"Geometric efficiency",
"High photon energy",
"Image quality",
"Imaging protocol",
"Lesion detection",
"Matrix size",
"Miscellaneous",
"Mode of acquisition",
"Nuclear Medicine Imaging",
"Parallel hole collimator",
"Pinhole collimator",
"Pulse height analyzer",
"Pulse-height spectrometry",
"Rotation orbit",
"Sensitivity of collimator",
"Sodium iodide crystal",
"Solid state detector",
"Solid-state detector",
"Spatial resolution",
"Specification",
"Specifications",
"Static acquisition",
"System resolution"
];

keywordsByTopic['4'] = [
"Artefact",
"COR",
"Correction map",
"Gamma spectrum",
"Image quality",
"Intrinsic flood field uniformity",
"Intrinsic flood image",
"Miscellaneous",
"NEMA",
"Phantom",
"QC test",
"Setup",
"Uniformity"
];

keywordsByTopic['5'] = [
"4D PET/CT",
"Acquisition mode",
"Artifact",
"C-11 tracer",
"Coincidence event",
"Count rate",
"Crystal",
"Cyclotron",
"Cyclotron product",
"Data Correction",
"F-18 fluoride",
"F-18 production",
"F-18 radionuclide",
"F-18 tracer",
"N-13 ammonia",
"O-15 water",
"Performance characteristic",
"PET camera",
"Photodetector",
"Positron annihilation",
"Proton beam",
"Quality control",
"Radionuclide",
"Rubidium-82",
"Sensitivity",
"Spatial resolution",
"SUV",
"Time-of-flight"
];

keywordsByTopic['6'] = [
"Artificial intelligence",
"Artificial neural network",
"Binary number",
"Computer",
"Convolutional neural network",
"DICOM",
"Digital image",
"Dynamic image processing",
"Graphical user interface",
"High-level computer language",
"Image arithmetic",
"Image display",
"Image filtering",
"Image interpolation",
"Interfile",
"Low-level computer language",
"Machine learning",
"Matrix size",
"Mode of execution",
"MUGA",
"Operation system",
"Operator of function",
"PACS",
"Rule-based reasoning",
"Thresholding",
"Units of information storage",
"Windowing"
];

keywordsByTopic['7'] = [
"Attenuation correction",
"Buttterworth filter",
"Collimator-detector response",
"Filtered backprojection",
"Image artefact",
"Image quality",
"Image reconstruction technique",
"Iterative reconstruction",
"Metz filter",
"Miscellaneous",
"Myocardial perfusion SPECT",
"Partial volume",
"Partial volume effect",
"Principles of SPECT",
"Reconstructed image",
"Reconstruction filter",
"Sinogram",
"Spatial resolution",
"SPECT",
"SPECT acquisition",
"SPECT reconstruction"
];

keywordsByTopic['8'] = [
"ANOVA",
"Association between variables",
"Bias in clinical trial",
"Box and Whisker plot",
"Box whisker plot",
"Choice of test",
"Clinical significance",
"Cohort study",
"Confidence interval",
"Confounding bias",
"Correlation",
"Diagnostic accuracy",
"Frequency data",
"Graph",
"Linear regression",
"Miscellaneous",
"Non-parametric tests",
"Normal range",
"Poisson distribution",
"Probability",
"Random sampling",
"Randomized control trial",
"Referral bias",
"Regression analysis",
"Relative risk",
"Reproducibity",
"ROC curve",
"Sample size",
"Significance",
"Spread of distribution",
"Standard deviation",
"Statistical mean",
"Statistical significance",
"Study design",
"t-test",
"Type I error",
"Variable"
];

keywordsByTopic['9'] = [
"Beam hardening",
"Dosimetry",
"Instrumentation",
"Interaction",
"Interaction of radiation with matter",
"Pathophysiology",
"Patient preparation",
"Procedure",
"Quality control",
"Rotating drum",
"Technique",
"X-ray energy"
];

keywordsByTopic['10'] = [
"Blood flow",
"Cardiac output",
"Extraction efficiency",
"F-18 fluoride",
"FDG",
"Fick principle",
"GFR",
"Liver function",
"Patlak-Rutland plot",
"Plasma volume",
"Potassium analogue",
"Rate constant",
"Renal background subtraction",
"Renal output efficiency",
"Renal transit time",
"Renkin-Crone",
"Sulphur colloid",
"Tracer principle"
];

keywordsByTopic['11'] = [
"Breast feeding",
"Cancer risk",
"Classified radiation workers",
"Daya Bay",
"Deterministic effects",
"Dose limits",
"Fetal exposure",
"HACoP",
"ICRP 2007",
"ICRP-103",
"Miscellaneous",
"Patient discharge",
"Principles of radiation protection",
"Radiation dose",
"Radiation dosimetry",
"Radiation hazards",
"Radiation risk",
"Radiation weighting factor",
"Radioactivity",
"Radiobiology",
"Shielding",
"SPECT/CT",
"Staff exposure",
"Stochastic effect",
"Storage",
"Tissue weighting factor"
];

keywordsByTopic['12'] = [
"Atomic nucleus",
"Attenuation",
"Beta decay",
"Decay factor",
"Decay mode",
"Electron",
"Electron capture",
"Equilibrium",
"Gallium-67",
"Gallium-68",
"Gamma decay",
"Gamma spectrum",
"Half-life",
"Interactions of radiation with matters",
"Iodine",
"Lutetium-177",
"Miscellaneous",
"Photoelectric effect",
"Photon",
"Positron",
"Radioactive decay",
"Radioactivity"
];

keywordsByTopic['13'] = [
"Beam hardening",
"CT artifact",
"CT noise",
"CT number",
"CT reconstruction",
"Hounsfield unit",
"Instrumentation",
"MRI technique",
"Pulse sequence",
"Sinogram",
"Spatial resolution"
];

keywordsByTopic['14'] = [
"Hybrid imaging",
"Image display",
"Measurement",
"Miscellaneous",
"Radiopharmaceutical"
];